### ISSUE TITLE
bun build --compile can't resolve pdfkit's #standard-fonts imports, breaking every packaged binary

### ISSUE THREAD

**Issue by alrayyes** [alrayyes/washy-washy-cli#231]
## What's broken

`main`'s `deb-install`, `rpm-install` and `aur-install` checks have failed on every run since 00bafc7 (2026-09-15 18:32 UTC), and every open Dependabot PR inherits the same failure regardless of what it actually changes — e.g. #224 (an unrelated `@stryker-mutator/core` devDependency bump).

The compiled binary crashes on startup:

```
error: Cannot find module '#standard-fonts/Helvetica' from '/$bunfs/root/washy-washy-cli-linux-amd64'
```

## Root cause

Bisected to 00bafc7, `fix(deps): bump @washy-washy/pdf from 2.3.8 to 2.4.2`. That release bumps `@react-pdf/renderer` from 4.6.1 to 4.9.0, which pulls in a newer `pdfkit` that resolves its bundled standard fonts through pdfkit's own `package.json#imports` map (`#standard-fonts/*`). That self-referencing subpath import only resolves correctly when pdfkit is loaded as its own package; `bun build --compile` (used in `build:binaries` and the CI packaging jobs) flattens everything into a single executable and the import fails to resolve at runtime.

`mutation`/`check`/`test` all stay green because they run against source via `bun test`, not the compiled binary — only the packaging jobs that actually run `bun build --compile` and then execute the result (`deb-install`, `rpm-install`, `aur-install`) catch it.

## Evidence

- First failure: https://github.com/alrayyes/washy-washy-cli/actions/runs/35008803635 (main, 2026-09-15T18:39Z)
- Last success: https://github.com/alrayyes/washy-washy-cli/actions/runs/35007272229 (main, 2026-09-15T18:24Z)
- Same failure on an unrelated PR: https://github.com/alrayyes/washy-washy-cli/actions/runs/35074147698 (#224)
- Regressing commit: 00bafc7

## Suggested next step

Either exclude/externalize pdfkit's standard-fonts assets from the `bun build --compile` bundle so the `#standard-fonts/*` imports resolve normally, or pin `@washy-washy/pdf` back until upstream bun/pdfkit compatibility is confirmed. Flagged to the `washy-washy-pdf` maintainer session too, since the regression originates in that package's `@react-pdf/renderer` bump.
